version: '3.7'
services:
  app:
    image: 'russian-philadelphia'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: philadelphia
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/philadelphia
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=philadelphia
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 5436:5432